# ===== Renderer =====

vo=gpu-next
gpu-api=vulkan
hwdec=auto-safe
vd-lavc-dr=yes
vulkan-async-compute=yes
vulkan-async-transfer=yes
video-output-levels=auto
target-prim=auto
target-trc=auto
dither-depth=auto


# ===== Debanding =====

deband=yes
deband-iterations=2
deband-threshold=40
deband-range=16
deband-grain=16


# ===== Scaling =====

scale=ewa_lanczos
dscale=mitchell
cscale=mitchell
scale-antiring=0.6
correct-downscaling=yes
linear-downscaling=no
sigmoid-upscaling=yes


# ===== Shaders =====

glsl-shaders="~~/shaders/ArtCNN_C4F16.glsl:~~/shaders/CfL_Prediction.glsl:~~/shaders/SSimDownscaler.glsl"
interpolation=no


# ===== Playback =====

keep-open=no
deinterlace=no
save-position-on-quit=yes
reset-on-next-file=audio-delay,mute,pause,speed,sub-delay,video-zoom,volume
watch-later-options-remove=sub-pos
watch-later-options-remove=osd-margin-y


# ===== UI =====

osc=no
border=no
msg-color=yes
term-osd-bar=yes
cursor-autohide=1000
osd-level=1
osd-bar=no
osd-font='FantasqueSans Mono'
osd-font-size=35
sub-font='Netflix Sans'
sub-font-size=32
sub-border-size=1
blend-subtitles=yes
screenshot-directory='~/Pictures/Screenshots'
screenshot-template='mpv-%f-%p'


# ===== Theme =====

background-color='#1e1e2e'
osd-back-color='#11111b'
osd-border-color='#11111b'
osd-color='#cdd6f4'
osd-shadow-color='#1e1e2e'
script-opts-append=stats-border_color=251818
script-opts-append=stats-font_color=f4d6cd
script-opts-append=stats-plot_bg_border_color=fab489
script-opts-append=stats-plot_bg_color=251818
script-opts-append=stats-plot_color=fab489


# ===== Profiles =====

[low-refresh]
profile-desc=low-refresh
profile-restore=copy-equal
profile-cond=get("display-fps", 0) > 0 and get("display-fps", 0) < 100
video-sync=display-resample
interpolation=yes
tscale=oversample

[interlaced]
profile-desc=interlaced
profile-restore=copy-equal
profile-cond=get("video-frame-info/interlaced", false)
deinterlace=yes

[uhd]
profile-desc=uhd
profile-restore=copy-equal
profile-cond=get("height", 0) >= 2160
deband=no

[extension.gif]
profile-desc=gif
profile-restore=copy-equal
cache=no
no-pause
loop-file=yes

[extension.webm]
profile-desc=webm
profile-restore=copy-equal
no-pause
loop-file=yes

[protocol.http]
profile-desc=http
hls-bitrate=max
cache=yes
no-cache-pause

[protocol.https]
profile-desc=https
profile=protocol.http

[protocol.ytdl]
profile-desc=ytdl
profile=protocol.http
