# https://sw.kovidgoyal.net/kitty/open_actions/

protocol file
mime image/*
action launch --type=overlay kitty +kitten icat --hold ${FILE_PATH}

protocol file
mime inode/directory
action launch --type=tab --cwd -- $FILE_PATH

protocol file
mime text/*
action launch --type=tab -- nvim -- $FILE_PATH

protocol file
ext yml,yaml,json,toml,md,markdown,py,js,ts,jsx,tsx,rs,go,lua,rb,conf,cfg,ini,xml,html,css,scss,sass,less,sql,graphql,proto,dockerfile,makefile,cmake,gradle,properties,env,gitignore,dockerignore,editorconfig,vim,nvim
action launch --type=tab -- nvim -- $FILE_PATH

protocol file
action launch --type=tab -- nvim -- $FILE_PATH
