remote_dir .local/share/kitty-ssh-kitten
terminfo_dir .local/share/terminfo
env ZDOTDIR=${HOME}/.config/zsh
remote_kitty if-needed
remote_browser yes
share_connections yes
shell_integration no-title
forward_remote_control yes
