remote_dir .local/share/kitty-ssh-kitten
terminfo_dir .local/share/terminfo
env ZDOTDIR=${HOME}/.config/zsh
env KITTY_INSTALLATION_DIR=${HOME}/.local/share/kitty-ssh-kitten
remote_kitty if-needed
share_connections yes
forward_remote_control yes
