# zones
tab_bar_zone_left            cwd_git
tab_bar_left_mode_indicator  yes
tab_bar_zone_right           tab_label title
tab_bar_left_icon            
tab_bar_left_ssh_icon        

# chrome glyphs
tab_bar_pill_border_left     
tab_bar_pill_border_right    
tab_bar_pill_separator       
tab_bar_ellipsis             …
tab_bar_content_separator    " · "
tab_bar_zone_text_bg         #181825

# git chrome
tab_bar_git_branch_color     #cba6f7
tab_bar_git_branch_icon_color #9399b2
tab_bar_git_directory_color  #cdd6f4
tab_bar_git_branch_icon      

# git status
tab_bar_git_status  stashed * #a6adc8
tab_bar_git_status  deleted ✘ #cba6f7
tab_bar_git_status  staged + #74c7ec
tab_bar_git_status  modified ! #f9e2af
tab_bar_git_status  renamed » #fab387
tab_bar_git_status  untracked ? #89b4fa
tab_bar_git_status  conflicted ~ #f38ba8
tab_bar_git_status  ahead ⇡ #a6e3a1
tab_bar_git_status  behind ⇣ #f38ba8

# mode indicator
tab_bar_mode_bg     #fab387
tab_bar_mode_name   leader 󰌌

