config:
  windows:
    envs:
      path:
      others:
        - ALIAE_CONFIG: 'C:\Users\cwel\.config\aliae.yaml'

    features:
      enable:
        - 'VirtualMachinePlatform'
        - 'Microsoft-Windows-Subsystem-Linux'
        - 'NetFx3'
        - 'NetFx4-AdvSrvs'
      disable:
        - 'MicrosoftWindowsPowerShellV2'

    startup:
      shortcuts:
        - name: 'kb'
          target: 'C:\Users\cwel\.local\bin\kb.ahk'

        - name: 'VcXsrv'
          target: 'C:\Users\cwel\scoop\apps\vcxsrv\current\vcxsrv.exe'
          args: '-multiwindow -clipboard -wgl -auth %XAUTHORITY%'

    symlinks:
      '%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json': 'home\dot_config\windows-terminal\settings.json'
