[mgr]
prepend_keymap = [
  { on = [
    "g",
    "l",
  ], run = 'shell "nvim $@ +GitFileHistory" --block', desc = "Git file history" },
  { on = 'E', run = 'shell "sudo -e $@" --block --confirm' },
  { on = 'R', run = "plugin rsync", desc = "rsync to host" },
  { on = "<C-p>", run = "shell -- qlmanage -p %s", desc = "Quick look (Darwin)" },
  { on = [
    "g",
    "j",
  ], run = "plugin recycle-bin -- open", desc = "Open trash directory" },
  { on = [
    "g",
    "J",
  ], run = "plugin recycle-bin", desc = "Trash menu" },

  { on = "l", run = "plugin augment-command -- enter", desc = "Enter directory or open file" },
  { on = "f", run = "plugin searchjump", desc = "Search jump (visible pane)" },
  { on = "/", run = "plugin fg -- rg", desc = "Search file contents (ripgrep)" },
  { on = [
    "s",
    "r",
  ], run = '''shell 'nvim +GrugFar' --block''', desc = "Find & replace (grug-far)" },
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" },
  { on = "M", run = "plugin mount", desc = "Mount manager" },
  { on = ";", run = "plugin custom-shell -- auto", desc = "Run a shell command" },
  { on = "T", run = "plugin toggle-pane max-preview", desc = "Maximize/restore preview" },
  { on = "+", run = "plugin zoom 1", desc = "Zoom in preview" },
  { on = "-", run = "plugin zoom -1", desc = "Zoom out preview" },
  { on = "<C-d>", run = "plugin diff", desc = "Diff selected with hovered" },
  { on = [
    "g",
    "i",
  ], run = "plugin lazygit", desc = "run lazygit" },
  { on = [
    "c",
    "p",
  ], run = "plugin command", desc = "Yazi command prompt" },
  { on = [
    "c",
    "m",
  ], run = "plugin chmod", desc = "Chmod on selected files" },
  { on = [
    "c",
    "a",
  ], run = "plugin augment-command -- archive", desc = "Archive selected files" },
  { on = [
    "g",
    "c",
  ], run = "plugin vcs-files", desc = "Show Git file changes" },
  { on = "<A-e>", run = "excluded toggle", desc = "Toggle excluded files visibility" },

  { on = [
    "g",
    "R",
  ], run = '''shell 'f=$(rga --files-with-matches --no-messages "" 2>/dev/null | fzf --preview "rga --pretty --context 5 {q} {}") && [ -n "$f" ] && ya emit reveal "$f"' --block''', desc = "rga: search inside binaries/archives" },

  { on = [
    "P",
    "s",
  ], run = "plugin projects save", desc = "Project: save" },
  { on = [
    "P",
    "l",
  ], run = "plugin projects load", desc = "Project: load" },
  { on = [
    "P",
    "P",
  ], run = "plugin projects load_last", desc = "Project: load last" },
  { on = [
    "P",
    "d",
  ], run = "plugin projects delete", desc = "Project: delete" },
  { on = [
    "P",
    "D",
  ], run = "plugin projects delete_all", desc = "Project: delete all" },

  { on = "u", run = "plugin restore", desc = "Restore last deleted" },
  { on = "U", run = "plugin restore -- --interactive", desc = "Restore (interactive)" },
]
