[mgr]
prepend_keymap = [
  { on = [
    "g",
    "l",
  ], run = 'shell "nvim $@ +GitFileHistory" --block', desc = "Git file history" },
  { on = 'E', run = 'shell "sudo -e $@" --block --confirm' },
  { on = [ "c", "s", ], run = "plugin rsync", desc = "rsync to host" },
  { on = 'R', run = "plugin omni-trash", desc = "Trash Menu" },
  { on = "l", run = "plugin augment-command.enter", desc = "Enter directory or open file" },
  { on = "f", run = "plugin searchjump", desc = "Search jump" },
  { on = "<C-f>", run = "filter --smart", desc = "Filter files" },
  { on = "<A-g>", run = "plugin yafg", desc = "Content search" },
  { on = [
    "c",
    "r",
  ], run = '''shell 'nvim +GrugFar' --block''', desc = "Find & replace (grug-far)" },
  { on = "F", run = "plugin smart-filter", desc = "Smart filter" },
  { on = "M", run = "plugin mount", desc = "Mount manager" },
  { on = "T", run = "plugin toggle-pane max-preview", desc = "Maximize/restore preview" },
  { on = "+", run = "plugin zoom 1", desc = "Zoom in preview" },
  { on = "-", run = "plugin zoom -1", desc = "Zoom out preview" },
  { on = "<C-d>", run = "plugin diff", desc = "Diff selected with hovered" },
  { on = [
    "g",
    "i",
  ], run = "plugin lazygit", desc = "run lazygit" },
  { on = [
    "c",
    "x",
  ], run = "plugin command", desc = "Command prompt" },
  { on = [
    "c",
    "m",
  ], run = "plugin chmod", desc = "Chmod on selected files" },
  { on = [
    "c",
    "a",
  ], run = "plugin augment-command.archive", desc = "Archive selected files" },
  { on = [
    "g",
    "s",
  ], run = "plugin vcs-files", desc = "Show Git file changes" },
  { on = "<A-e>", run = "excluded toggle", desc = "Toggle excluded files visibility" },

  { on = [
    "g",
    "R",
  ], run = '''shell 'f=$(rga --files-with-matches --no-messages "" 2>/dev/null | fzf --preview "rga --pretty --context 5 {q} {}") && [ -n "$f" ] && ya emit reveal "$f"' --block''', desc = "rga: search inside binaries/archives" },
  { on = [ 
    "<A-y>", 
  ], run = "plugin copy-file-contents", desc = "Copy contents of file" },
  { on = [
    "<C-p>",
    "s",
  ], run = "plugin projects save", desc = "Save current project" },
  { on = [
    "<C-p>",
    "l",
  ], run = "plugin projects load", desc = "Load project" },
  { on = [
    "<C-p>",
    "P",
  ], run = "plugin projects load_last", desc = "Load last project" },
  { on = [
    "<C-p>",
    "d",
  ], run = "plugin projects delete", desc = "Delete project" },
  { on = [
    "<C-p>",
    "D",
  ], run = "plugin projects delete_all", desc = "Delete all projects" },
  { on = [
    "<C-p>",
    "m",
  ], run = "plugin projects 'merge current'", desc = "Merge current tab to other projects" },
  { on = [
    "<C-p>",
    "M",
  ], run = "plugin projects 'merge all'", desc = "Merge current project to other projects" },

  { on = "u", run = "plugin restore", desc = "Restore last deleted" },
  { on = "U", run = "plugin restore -- --interactive", desc = "Restore (interactive)" },
]
