[flavor]
dark = "catppuccin-mocha"

[icon]
prepend_dirs = [
  { name = "src", text = "", },
  { name = ".Trash", text = "", },
  { name = ".cache", text = "", },
  { name = ".ssh", text = "󰢬", },
  { name = ".local", text = "󰉌", },
  { name = "Applications", text = "󰀻", fg = "#89b4fa" },
  { name = ".config", text = "", fg = "#89b4fa" },
  { name = "Desktop", text = "", fg = "#89b4fa" },
  { name = "Documents", text = "", fg = "#89b4fa" },
  { name = "Downloads", text = "", fg = "#89b4fa" },
  { name = "Library", text = "", fg = "#89b4fa" },
  { name = "Movies", text = "", fg = "#89b4fa" },
  { name = "Music", text = "", fg = "#89b4fa" },
  { name = "Pictures", text = "", fg = "#89b4fa" },
  { name = "Public", text = "", fg = "#89b4fa" },
  { name = "Videos", text = "", fg = "#89b4fa" },
]
