#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
ratio = [1, 2, 3]
sort_by = "natural"
sort_dir_first = true
sort_sensitive = false
sort_reverse = false
sort_translit = false
linemode = "size"
show_hidden = true
show_symlink = true
scrolloff = 5
mouse_events = ["click", "scroll", "touch", "move", "drag"]
title_format = "{cwd}"

[files]
excludes = [
  { urn = [
    ".DS_Store",
    ".localized",
    ".hushlogin",
    "NTUSER*",
    "ntuser*",
    "Thumbs.db",
    "lost+found",
    ".snapshots",
    ".keep",
    ".Trash",
    ".Trash-*",
    ".pki",
    ".steampath",
    ".steampid",
    ".nextcloudsync.log",
    ".sync_*.db*",
    ".sync-exclude.lst",
    ".stfolder",
    ".stignore",
    "__pycache__",
    "*.pyc",
    "*.pyo",
    "node_modules",
    ".venv",
    "venv",
    ".swiftpm",
    ".obsidian-cli.sock",
  ], in = "*" },
  { urn = ["Shared"], in = "/Users" },
  { urn = ["ncdata"], in = "/mnt" },
]

[opener]
extract = [
  { run = 'ya pub augmented-extract --list %s', desc = "Extract here (augment-command)" },
]

[plugin]
prepend_fetchers = [
  { group = "git", url = "*", run = "git" },
  { group = "git", url = "*/", run = "git" },
  { group = "mime", url = "local://*", run = "mime-ext.local", prio = "high" },
  { group = "mime", url = "remote://*", run = "mime-ext.remote", prio = "high" },
]

prepend_preloaders = [
  { mime = "application/openxmlformats-officedocument.*", run = "office" },
  { mime = "application/oasis.opendocument.*", run = "office" },
  { mime = "application/ms-*", run = "office" },
  { mime = "application/msword", run = "office" },
  { url = "*.docx", run = "office" },
]

prepend_previewers = [
  { url = "*.csv", run = 'piper -- xan view "$1"' },
  { mime = "text/*", run = 'piper -- bat -p --color=always "$1"' },
  # { mime = "application/{*zip,tar,bzip2,7z*,rar,xz,zstd,java-archive}", run = "ouch --archive-icon='🗄️ ' --show-file-icons --list-view" },
  { mime = "application/openxmlformats-officedocument.*", run = "office" },
  { mime = "application/oasis.opendocument.*", run = "office" },
  { mime = "application/ms-*", run = "office" },
  { mime = "application/msword", run = "office" },
  { url = "*.docx", run = "office" },
]
