#:schema https://yazi-rs.github.io/schemas/yazi.json

[mgr]
ratio = [1, 2, 3]
sort_by = "natural"
sort_dir_first = true
sort_sensitive = false
sort_reverse = false
sort_translit = false
linemode = "size_only"
show_hidden = true
show_symlink = true
scrolloff = 5
mouse_events = ["click", "scroll", "touch", "move", "drag"]
title_format = "{cwd}"

[files]
excludes = [
  { url = [
    "**/.DS_Store",
    "**/.localized",
    "**/.hushlogin",
    "**/NTUSER*",
    "**/Thumbs.db",
    "**/.keep",
    "**/.steampath",
    "**/.steampid",
    "**/.nextcloudsync.log",
    "**/.sync_*.db*",
    "**/.sync-exclude.lst",
    "**/.stignore",
    "**/.obsidian-cli.sock",
    "*.pyc",
    "*.pyo",
    "**/lost+found/",
    "**/.snapshots/",
    "**/.Trash/",
    "**/.Trash-*/",
    "**/.pki/",
    "**/.stfolder/",
    "**/__pycache__/",
    "**/node_modules/",
    "**/.venv/",
    "**/venv/",
  ], in = "*" },
  { url = [
    "**/Shared/",
  ], in = "/Users" },
  { url = [
    "**/ncdata/",
  ], in = "/mnt" },
]

[open]
prepend_rules = [
  { mime = "trash/**", use = ["trash", "open"] },
]

[opener]
open = [
  { run = "xdg-open %s1", desc = "Open", block = true, for = "linux" },
  { run = "open %s", desc = "Open", for = "macos" },
]

extract = [
  { run = 'ya pub augmented-extract --list %s', desc = "Extract here (augment-command)" },
]

download = [
  { run = "ya emit download %S", desc = "Download" },
  { run = "ya emit download --open %S", desc = "Download and open" },
]

[plugin]
prepend_fetchers = [
  { group = "git", url = "*", run = "git" },
  { group = "git", url = "*/", run = "git" },
]

prepend_preloaders = [
  { mime = "application/openxmlformats-officedocument.*", run = "office" },
  { mime = "application/oasis.opendocument.*", run = "office" },
  { mime = "application/ms-*", run = "office" },
  { mime = "application/msword", run = "office" },
  { url = "*.docx", run = "office" },
]

prepend_previewers = [
  { url = "*.csv", run = 'piper -- xan view "$1"' },
  { mime = "text/*", run = 'piper -- bat -p --color=always "$1"' },
  { mime = "application/{*xml,xml-dtd,ecmascript,javascript,sql,csh,tcl,latex,rtf,pgp-signature,pgp-keys,graphql,*+json}", run = 'piper -- bat -p --color=always "$1"' },
  { mime = "application/openxmlformats-officedocument.*", run = "office" },
  { mime = "application/oasis.opendocument.*", run = "office" },
  { mime = "application/ms-*", run = "office" },
  { mime = "application/msword", run = "office" },
  { url = "*.docx", run = "office" },
]
