[pyprland]
plugins = ["scratchpads", "magnify"]

[scratchpads.volume]
command = "pavucontrol"
# unfocus = "hide"
position = "69% 8%"
lazy = true

[scratchpads.bluetooth]
command = "overskride"
animation = "fromRight"
margin = 20
lazy = true

[scratchpads.wifi]
command = "iwgtk"
animation = "fromRight"
margin = 20
lazy = true

[scratchpads.network]
command = "nm-connection-editor"
animation = "fromRight"
margin = 20
lazy = true

[scratchpads.btop]
command = "kitty --class scratchpad-large btop"
lazy = true

[scratchpads.topgrade-system]
command = "kitty --class scratchpad-large topgrade -k --only system"
lazy = true

[scratchpads.topgrade-all]
command = "kitty --class scratchpad-large topgrade -k --no-self-update"
lazy = true
