#!/bin/bash

screensaver_in_focus() {
  hyprctl activewindow -j | jq -e '.class == "tte.screenie"' >/dev/null 2>&1
}

exit_screensaver() {
  hyprctl keyword cursor:invisible false
  pkill -x tte 2>/dev/null
  pkill -f "tte.screenie" 2>/dev/null
  exit 0
}

trap exit_screensaver SIGINT SIGTERM SIGHUP SIGQUIT

printf '\033]11;rgb:00/00/00\007' # Set background color to black

hyprctl keyword cursor:invisible true &>/dev/null

initial_cursorpos=$(hyprctl cursorpos 2>/dev/null || echo "0, 0")

while true; do
  tte -i ~/.config/hypr/scripts/screensaver.txt \
    --frame-rate 120 --canvas-width 0 --canvas-height 0 --reuse-canvas --anchor-canvas c --anchor-text c \
    --random-effect --exclude-effects matrix synthgrid sweep \
    --no-eol --no-restore-cursor &

  while pgrep -x tte >/dev/null; do
    curr_cursorpos=$(hyprctl cursorpos 2>/dev/null || echo "0, 0")
    if [[ "$curr_cursorpos" != "$initial_cursorpos" ]]; then
      exit_screensaver
    fi

    if read -n 1 -t 1 || ! screensaver_in_focus; then
      exit_screensaver
    fi
  done
done
