#!/usr/bin/env sh

# Set terminal title to current song
printf '\e]0;%.25s\a' "${TITLE:-${FILE##*/}}" >/dev/tty

# Increment play count
# sticker=$(rmpc sticker get "$FILE" "playCount" | jq -r '.value')
# if [ -z "$sticker" ]; then
#     rmpc sticker set "$FILE" "playCount" "1"
# else
#     rmpc sticker set "$FILE" "playCount" "$((sticker + 1))"
# fi
