#:schema https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json

version = 3
final_space = true
auto_upgrade = true
console_title_template = "{{if .Root}} \u26a1 {{end}}{{ .Segments.Path.Path }}"
[palette]
Base = '#1e1e2e'
Blue = '#89b4fa'
Crust = '#11111b'
Flamingo = '#f2cdcd'
Green = '#a6e3a1'
Lavender = '#b4befe'
Mantle = '#181825'
Maroon = '#eba0ac'
Mauve = '#cba6f7'
Overlay0 = '#6c7086'
Overlay1 = '#7f849c'
Overlay2 = '#9399b2'
Peach = '#fab387'
Pink = '#f5c2e7'
Red = '#f38ba8'
Rosewater = '#f5e0dc'
Sapphire = '#74c7ec'
Sky = '#89dceb'
Subtext0 = '#a6adc8'
Subtext1 = '#bac2de'
Surface0 = '#313244'
Surface1 = '#45475a'
Surface2 = '#585b70'
Teal = '#94e2d5'
Text = '#cdd6f4'
Yellow = '#f9e2af'
os = '#ACB0BE'

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = ' {{ .Icon }}  '
foreground = 'p:os'
type = 'os'
style = 'plain'


[secondary_prompt]
template = '❯❯ '
foreground = 'p:Teal'

[transient_prompt]
template = '❯ '
background = 'transparent'
foreground_templates = [
  '{{if gt .Code 0}}p:Red{{end}}',
  '{{if eq .Code 0}}p:Green{{end}}',
]
newline = true

[blocks.segments.properties]
alpine = ''
arch = ''
centos = ''
debian = ''
elementary = ''
fedora = ''
gentoo = ''
linux = ''
macos = ''
manjaro = ''
mint = ''
opensuse = ''
raspbian = ''
ubuntu = ''
windows = ''

[[blocks.segments]]
template = ' admin '
type = 'root'
style = 'plain'
foreground = 'p:Overlay0'

[[blocks.segments]]
template = '{{ .Path }} '
foreground = 'p:Blue'
type = 'path'
style = 'plain'

[blocks.segments.properties]
style = 'agnoster_full'

[[blocks.segments]]
template = '{{ .HEAD }}<p:Mauve>{{ if or (.Working.Changed) (.Staging.Changed) }} {{ .Working.String }}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }} |{{ end }}</><p:Green>{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}</><p:Peach>  {{ .StashCount }}{{ end }}</> <p:Red>{{ if gt .Behind 0 }}⇣{{ end }}</><p:Green>{{ if gt .Ahead 0 }}⇡{{ end }}</> '
foreground = 'p:Lavender'
type = 'git'
style = 'powerline'

[blocks.segments.properties]
branch_icon = ' '
cherry_pick_icon = ' '
commit_icon = ' '
fetch_status = true
fetch_upstream_icon = false
fetch_stash_count = true
merge_icon = ' '
no_commits_icon = ' '
rebase_icon = ' '
revert_icon = ' '
tag_icon = ' '
cache_duration = 'none'

[[blocks]]
type = 'rprompt'
overflow = 'hide'

[[blocks.segments]]
template = ' {{if .WSL}} {{ end}} ({{ (div ((sub .PhysicalTotalMemory .PhysicalAvailableMemory)|float64) 1073741824.0) }}/{{ (div .PhysicalTotalMemory 1073741824.0) }}GB) '
foreground = 'p:Subtext0'
type = 'sysinfo'
style = 'plain'

[[blocks.segments]]
template = '{{ .FormattedMs }}s'
foreground = 'p:Sky'
background = 'transparent'
type = 'executiontime'
style = 'plain'

[blocks.segments.properties]
cache_duration = 'none'
style = 'dallas'
threshold = 0

[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
leading_diamond = ''
trailing_diamond = ''
template = '   {{ if ne .Status "stopped" }} {{ .Artist }} - {{ .Track }}{{ end }} '
foreground = 'p:Green'
background = 'p:Surface0'
type = 'spotify'
style = 'diamond'


[[blocks]]
type = 'prompt'
alignment = 'left'
newline = true

[[blocks.segments]]
template = '❯'
type = 'text'
style = 'plain'
foreground_templates = [
  '{{ if gt .Code 0 }}p:Red{{ end }}',
  '{{ if eq .Code 0}}p:Mauve{{ end }}',
]

# [[blocks.segments]]
# template = '  {{ .Context }} '
# foreground = 'p:Sapphire'
# background = 'transparent'
# type = 'docker'
# style = 'accordion'

# [blocks.segments.properties]
# cache_duration = 'none'
