auto_sync    = true
update_check = true
# sync_address = "https://api.atuin.sh"
sync_frequency = "10m"

## prefix, fulltext, fuzzy, skim
search_mode = "fuzzy"

## global, host, session, directory
# filter_mode = "global"
# filter_mode_shell_up_key_binding = "global"

## auto, full, compact
style = "auto"

## 0 to always go full screen
inline_height = 40

## enable or disable showing a preview of selected command useful when the command is cut off
# show_preview = false

## what to do when the escape key is pressed when searching | return-original, return-query
# exit_mode = "return-original"

## emacs, subl
# word_jump_mode = "emacs"

# word_chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

# scroll_context_lines = 1

# ctrl_n_shortcuts = false

## prevent commands matching any of these regexes from being written to history.
## Note that these regular expressions are unanchored, i.e. if they don't start
## with ^ or end with $, they'll match anywhere in the command.
## For details on the supported regular expression syntax, see
## https://docs.rs/regex/latest/regex/#syntax
# history_filter = [
#   "^secret-cmd",
#   "^innocuous-cmd .*--secret=.+"
# ]

## prevent commands run with cwd matching any of these regexes from being written
## to history. Note that these regular expressions are unanchored, i.e. if they don't
## start with ^ or end with $, they'll match anywhere in CWD.
## For details on the supported regular expression syntax, see
## https://docs.rs/regex/latest/regex/#syntax
# cwd_filter = [
#   "^/very/secret/area"
# ]

enter_accept = true

## vim-mode
#keymap_mode = "vim-insert"

[sync]
    records = true

[theme]
    name = "catppuccin-mocha-teal"
