[default]
F13{H} >> ArrowLeft
F13{J} >> ArrowDown
F13{K} >> ArrowUp
F13{L} >> ArrowRight

MoveMode = Virtual1

CapsLock{!200ms} !200ms CapsLock{!200ms} >> MoveMode
MoveMode{J} >> $(niri msg action move-column-to-workspace-down) !MoveMode
MoveMode{K} >> $(niri msg action move-column-to-workspace-up)   !MoveMode

MoveMode{Any} >> Any !MoveMode
