[default]
ControlRight{H} >> ArrowLeft
ControlRight{J} >> ArrowDown
ControlRight{K} >> ArrowUp
ControlRight{L} >> ArrowRight
ControlRight{D} >> $(niri msg action clear-dynamic-cast-target)

MoveMode = Virtual1

CapsLock{!200ms} !200ms CapsLock{!200ms} >> MoveMode
MoveMode{J} >> $(niri msg action move-column-to-workspace-down) !MoveMode
MoveMode{K} >> $(niri msg action move-column-to-workspace-up)   !MoveMode

MoveMode{Any} >> Any !MoveMode
