config:
  windows:
    envs:
      path:
        - '%LOCALAPPDATA%\nvim-data\mason\bin'
        # - '%LOCALAPPDATA%\mise\shims'
        - '%USERPROFILE%\.local\share\mise\shims'
        - '%USERPROFILE%\scoop\apps\git\current\usr\bin'
        - '%USERPROFILE%\.local\bin'
      others:
        DOCKER_HOST: 'tcp://psock:2375'
        HOME: '%USERPROFILE%'
        XDG_CONFIG_HOME: '%USERPROFILE%\.config'
        XDG_PROJECTS_DIR: '%USERPROFILE%\projects'
        XDG_CACHE_HOME: '%USERPROFILE%\.cache'
        XDG_DATA_HOME: '%USERPROFILE%\.local\share'
        XDG_STATE_HOME: '%USERPROFILE%\.local\state'
        XDG_BIN_HOME: '%USERPROFILE%\.local\bin'
        YAZI_CONFIG_HOME: '%USERPROFILE%\.config\yazi'
        YAZI_FILE_ONE: '%USERPROFILE%\scoop\apps\git\current\usr\bin\file.exe'
        KOMOREBI_CONFIG_HOME: '%USERPROFILE%\.config\komorebi'
        EZA_CONFIG_DIR: '%USERPROFILE%\.config\eza'
        VAGRANT_DEFAULT_PROVIDER: 'virtualbox'
        DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
        GH_DASH_CONFIG: '%USERPROFILE%\.config\gh-dash\config.yml'
        CARGO_HOME: '%USERPROFILE%\.local\share\cargo'
        RUSTUP_HOME: '%USERPROFILE%\.local\share\rustup'
        GOPATH: '%USERPROFILE%\.local\share\go'
        NPM_CONFIG_CACHE: '%USERPROFILE%\.cache\npm'
        YARN_CACHE_FOLDER: '%USERPROFILE%\.cache\npm'
        PNPM_HOME: '%USERPROFILE%\.local\share\pnpm'

    features:
      enable:
        - 'VirtualMachinePlatform'
        - 'Microsoft-Windows-Subsystem-Linux'
        - 'NetFx3'
        - 'NetFx4-AdvSrvs'
      disable:
        - 'MicrosoftWindowsPowerShellV2'

    startup:
      shortcuts:
        - name: 'ctrl-h'
          target: '%USERPROFILE%\.local\bin\ctrl-h.exe'

        - name: 'VcXsrv'
          target: '%USERPROFILE%\scoop\apps\vcxsrv\current\vcxsrv.exe'
          args: '-multiwindow -clipboard -wgl -auth "%USERPROFILE%\.Xauthority"'
