config:
  windows:
    envs:
      path:
        - '%LOCALAPPDATA%\nvim-data\mason\bin'
        # - '%LOCALAPPDATA%\mise\shims'
        - '%USERPROFILE%\.local\share\mise\shims'
        - '%USERPROFILE%\scoop\apps\git\current\usr\bin'
        - '%USERPROFILE%\.local\bin'
      others:
        YAZI_CONFIG_HOME: '%USERPROFILE%\.config\yazi'
        YAZI_FILE_ONE: '%USERPROFILE%\scoop\apps\git\current\usr\bin\file.exe'
        KOMOREBI_CONFIG_HOME: '%USERPROFILE%\.config\komorebi'
        EZA_CONFIG_DIR: '%USERPROFILE%\.config\eza'
        VAGRANT_DEFAULT_PROVIDER: 'virtualbox'
        DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
        GH_DASH_CONFIG: '%USERPROFILE%\.config\gh-dash\config.yml'
        GOPATH: 'C:\Users\cwel\.go'
        XDG_CONFIG_HOME: '%USERPROFILE%\.config'
        XDG_PROJECTS_DIR: '%USERPROFILE%\projects'
        XDG_CACHE_HOME: '%USERPROFILE%\.cache'
        XDG_DATA_HOME: '%USERPROFILE%\.local\share'
        HOME: '%USERPROFILE%'
        DOCKER_HOST: 'tcp://psock:2375'

    features:
      enable:
        - 'VirtualMachinePlatform'
        - 'Microsoft-Windows-Subsystem-Linux'
        - 'NetFx3'
        - 'NetFx4-AdvSrvs'
      disable:
        - 'MicrosoftWindowsPowerShellV2'
