config:
  windows:
    envs:
      path:
        - '%LOCALAPPDATA%\nvim-data\mason\bin'
        # - '%LOCALAPPDATA%\mise\shims'
        - 'C:\Users\cwel\.local\share\mise\shims'
        - 'C:\Users\cwel\scoop\apps\git\current\usr\bin'
        - 'C:\Users\cwel\.local\bin'
      others:
        DOCKER_HOST: 'tcp://psock:2375'
        HOME: 'C:\Users\cwel'
        XDG_CONFIG_HOME: 'C:\Users\cwel\.config'
        XDG_PROJECTS_DIR: 'C:\Users\cwel\projects'
        XDG_CACHE_HOME: 'C:\Users\cwel\.cache'
        XDG_DATA_HOME: 'C:\Users\cwel\.local\share'
        XDG_STATE_HOME: 'C:\Users\cwel\.local\state'
        XDG_BIN_HOME: 'C:\Users\cwel\.local\bin'
        XDG_RUNTIME_DIR: 'C:\Users\cwel\AppData\Local\Temp'
        YAZI_CONFIG_HOME: 'C:\Users\cwel\.config\yazi'
        YAZI_FILE_ONE: 'C:\Users\cwel\scoop\apps\git\current\usr\bin\file.exe'
        KOMOREBI_CONFIG_HOME: 'C:\Users\cwel\.config\komorebi'
        AWS_CONFIG_FILE: 'C:\Users\cwel\.local\share\aws\config'
        AWS_DATA_PATH: 'C:\Users\cwel\.local\share\aws'
        AWS_SHARED_CREDENTIALS_FILE: 'C:\Users\cwel\.local\share\aws\credentials'
        EZA_CONFIG_DIR: 'C:\Users\cwel\.config\eza'
        GNUPGHOME: 'C:\Users\cwel\.local\share\gnupg'
        VBOX_USER_HOME: 'C:\Users\cwel\.local\share\virtualbox'
        VAGRANT_HOME: 'C:\Users\cwel\.local\share\vagrant'
        VAGRANT_DEFAULT_PROVIDER: 'virtualbox'
        DOCKER_CONFIG: 'C:\Users\cwel\.config\docker'
        DOTNET_CLI_HOME: 'C:\Users\cwel\.local\share\dotnet'
        DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
        GH_DASH_CONFIG: 'C:\Users\cwel\.config\gh-dash\config.yml'
        LESSHISTFILE: 'C:\Users\cwel\.cache\.lesshsts'
        CARGO_HOME: 'C:\Users\cwel\.local\share\cargo'
        RUSTUP_HOME: 'C:\Users\cwel\.local\share\rustup'
        GOPATH: 'C:\Users\cwel\.local\share\go'
        NPM_CONFIG_CACHE: 'C:\Users\cwel\.cache\npm'
        YARN_CACHE_FOLDER: 'C:\Users\cwel\.cache\npm'
        PNPM_HOME: 'C:\Users\cwel\.local\share\pnpm'
        XAUTHORITY: 'C:\Users\cwel\.local\state\.Xauthority'

    features:
      enable:
        - 'VirtualMachinePlatform'
        - 'Microsoft-Windows-Subsystem-Linux'
        - 'NetFx3'
        - 'NetFx4-AdvSrvs'
      disable:
        - 'MicrosoftWindowsPowerShellV2'

    startup:
      shortcuts:
        - name: 'ctrl-h'
          target: 'C:\Users\cwel\.local\bin\ctrl-h.exe'

        - name: 'VcXsrv'
          target: 'C:\Users\cwel\scoop\apps\vcxsrv\current\vcxsrv.exe'
          args: '-multiwindow -clipboard -wgl -auth "C:\Users\cwel\.Xauthority"'

    symlinks:
      '%LOCALAPPDATA%\Packages\Microsoft.WindowsTerminal_8wekyb3d8bbwe\LocalState\settings.json': 'home\dot_config\windows-terminal\settings.json'
