config:
  windows:
    envs:
      path:
        - '%LOCALAPPDATA%\nvim-data\mason\bin'
        - '%LOCALAPPDATA%\mise\shims'
        - '%USERPROFILE%\scoop\apps\git\current\usr\bin'
        - '%USERPROFILE%\.local\bin'
      others:
        YAZI_CONFIG_HOME: '%USERPROFILE%\.config\yazi'
        YAZI_FILE_ONE: '%USERPROFILE%\scoop\apps\git\current\usr\bin\file.exe'
        KOMOREBI_CONFIG_HOME: '%USERPROFILE%\.config\komorebi'
    features:
      enable:
        - 'VirtualMachinePlatform'
        - 'Microsoft-Windows-Subsystem-Linux'
        - 'NetFx3'
        - 'NetFx4-AdvSrvs'
      disable:
        - 'MicrosoftWindowsPowerShellV2'
