"$schema" = "https://starship.rs/config-schema.json"

add_newline = false
command_timeout = 500
continuation_prompt = "[❯❯ ](subtext0)"
palette = "mocha"
follow_symlinks = false

format = """
$directory\
$shell\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$env_var \
$container \
$all \
$status\
$cmd_duration\
$jobs\
$os\
$hostname\
$line_break\
$username$character"""

[env_var.ZMX_SESSION]
variable = 'ZMX_SESSION'
format = '[]($style)'
style = 'mauve'

[profiles]
transient = """
$character\
"""

rtransient = """
$status\
$cmd_duration\
"""

[os]
disabled = true
format = '[$symbol ](lavender)'

[fill]
disabled = false
symbol = " "

[status]
symbol = '✘ '
map_symbol = true
format = "[$symbol$status]($style) "
style = 'red'
disabled = false

[line_break]
disabled = false

[container]
format = ' [$symbol \[$name\]]($style) '
symbol = ''

[character]
# error_symbol   = "[](mauve)"
success_symbol = "[❯](peach)"
vimcmd_symbol = "[❮](peach)"

[battery]
disabled = true
full_symbol = '🔋 '
charging_symbol = '⚡️ '
discharging_symbol = '💀 '

[username]
disabled = true
aliases = { "Administrator" = '󱐋 ' }
format = '[$user]($style)'
style_root = 'mauve'
style_user = 'yellow'
# detect_env_vars = ['SSH_CONNECTION', '!SSH_CONNECTION']

[shell]
disabled = true
fish_indicator = '󰈺'
format = '[$indicator]($style)'
powershell_indicator = ''
style = 'teal'
unknown_indicator = ''
zsh_indicator = ''

[cmd_duration]
disabled = false
format = "[$duration]($style)"
style = "sapphire"

[directory]
fish_style_pwd_dir_length = 2
format = '[$path]($style)[$read_only]($read_only_style) '
read_only = " "
read_only_style = 'overlay1'
style = "blue"
truncation_length = 2
use_os_path_sep = false

[hostname]
disabled = true
ssh_only = true
format = "[$hostname]($style)"
ssh_symbol = "󰥛"
style = 'teal'

[git_state]
am = "󰲾"
bisect = "󱢇"
cherry_pick = " "
format = ' [$state( $progress_current/$progress_total)]($style)'
merge = ""
rebase = ""
revert = " "
style = "red"

[git_status]
format = "[$all_status$ahead_behind]($style) "
conflicted = '[ ~${count}](red)'
ahead = "[ ⇡${count}](green)"
behind = "[ ⇣${count}](red)"
diverged = "[ ⇕⇡${ahead_count}](teal)[⇣${behind_count}](peach)"
untracked = "[ ?${count}](blue)"
stashed = "[ *${count}](subtext0)"
modified = "[ !${count}](yellow)"
staged = "[ +${count}](sapphire)"
renamed = "[ »${count}](peach)"
deleted = "[ ✘${count}](mauve)"

[git_branch]
format = '[$symbol](overlay2)[$branch](mauve)'
symbol = ' '
truncation_length = 24
truncation_symbol = "…"
#ignore_branches = ['master','main']

[git_commit]
format = "[@$hash]($style) "
style = "green"
only_detached = true
tag_disabled = false
tag_symbol = '  '

[git_metrics]
disabled = true
added_style = "green"
deleted_style = "red"
format = "([+$added]($added_style) )([-$deleted]($deleted_style) )"

[aws]
style = 'yellow'
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'

[azure]
style = 'blue'
format = '[$symbol($subscription)]($style) '

[buf]
style = 'blue'
format = '[$symbol($version )]($style)'

[bun]
style = 'red'
format = '[$symbol($version )]($style)'

[c]
style = '149'
format = '[$symbol($version(-$name) )]($style)'

[cmake]
style = 'blue'
format = '[$symbol($version )]($style)'

[cobol]
style = 'blue'
format = '[$symbol($version )]($style)'

[conda]
style = 'green'
format = '[$symbol$environment]($style) '

[crystal]
style = 'red'
symbol = ' '
format = '[$symbol($version )]($style)'

[daml]
style = 'cyan'
format = '[$symbol($version )]($style)'

[dart]
style = 'blue'
symbol = ' '
format = '[$symbol($version )]($style)'

[deno]
style = 'green'
format = '[$symbol($version )]($style)'

[direnv]
style = 'orange'

[docker_context]
style = 'blue'
symbol = ' '
format = '[$symbol$context]($style) '

[dotnet]
style = 'blue'
format = '[$symbol($version )( $tfm )]($style)'

[elixir]
style = 'purple'
symbol = ' '
format = '[$symbol($version \(OTP $otp_version\) )]($style)'

[elm]
style = 'cyan'
symbol = ' '
format = '[$symbol($version )]($style)'

[erlang]
style = 'red'
format = '[$symbol($version )]($style)'

[fennel]
style = 'green'
format = '[$symbol($version )]($style)'

[gcloud]
disabled = true
symbol = ' '
style = 'blue'
format = '[$symbol$account(@$domain)(\($region\))]($style) '

[gleam]
style = '#FFAFF3'
format = '[$symbol($version )]($style)'

[golang]
style = 'cyan'
not_capable_style = 'red'
symbol = ' '
format = '[$symbol($version )]($style)'

[guix_shell]
style = 'yellow'
format = '[$symbol]($style) '

[gradle]
style = 'bright-cyan'
symbol = '⬡ '
format = '[$symbol($version )]($style)'

[haskell]
style = 'purple'
format = '[$symbol($version )]($style)'

[haxe]
style = 'fg:202'
format = '[$symbol($version )]($style)'

[helm]
style = 'white'
format = '[$symbol($version )]($style)'

[java]
symbol = ' '
format = '[$symbol($version )]($style)'

[julia]
style = 'purple'
format = '[$symbol($version )]($style)'

[kotlin]
style = 'blue'
symbol = '🅺 '
format = '[$symbol($version )]($style)'

[kubernetes]
style = 'cyan'
format = '[$symbol$context( \($namespace\))]($style) '

[lua]
style = 'cyan'
symbol = ' '
format = '[$symbol($version )]($style)'

[meson]
style = 'blue'
format = '[$symbol$project]($style) '

[nats]
style = 'purple'

[nim]
style = 'yellow'
format = '[$symbol($version )]($style)'

[nix_shell]
style = 'blue'
format = '[$symbol$state( \($name\))]($style) '

[nodejs]
style = 'green'
not_capable_style = 'red'
format = '[$symbol($version )]($style)'

[ocaml]
style = 'yellow'
symbol = ' '
format = '[$symbol($version )(\($switch_indicator$switch_name\) )]($style)'

[odin]
style = 'bright-blue'
format = '[$symbol($version )]($style)'

[opa]
style = 'blue'
format = '[$symbol($version )]($style)'

[openstack]
style = 'yellow'
format = '[$symbol$cloud(\($project\))]($style) '

[package]
style = '208'
format = '[$symbol($version )]($style)'

[perl]
style = '149'
symbol = ' '
format = '[$symbol($version )]($style)'

[php]
style = '147'
format = '[$symbol($version )]($style)'

[pulumi]
style = '5'
format = '[$symbol($username@)$stack]($style) '

[purescript]
style = 'white'
format = '[$symbol($version )]($style)'

[python]
style = 'yellow'
symbol = ' '
format = '[${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'

[quarto]
style = '#75AADB'
format = '[$symbol($version )]($style)'

[rlang]
style = 'blue'
format = '[$symbol($version )]($style)'

[raku]
style = '149'
format = '[$symbol($version-$vm_version )]($style)'

[red]
style = 'red'
format = '[$symbol($version )]($style)'

[ruby]
style = 'red'
symbol = ' '
format = '[$symbol($version )]($style)'

[rust]
style = 'red'
symbol = ' '
format = '[$symbol($version )]($style)'

[scala]
format = '[${symbol}(${version} )]($style)'

[singularity]
format = '[$symbol\[$env\]]($style) '

[solidity]
style = 'blue'
format = '[$symbol($version )]($style)'

[spack]
format = '[$symbol$environment]($style) '

[swift]
style = '202'
symbol = ' '
format = '[$symbol($version )]($style)'

[terraform]
style = '105'
symbol = '🛠 '
format = '[$symbol$workspace]($style) '

[typst]
style = '#0093A7'
format = '[$symbol($version )]($style)'

[vagrant]
style = 'cyan'
format = '[$symbol($version )]($style)'

[vlang]
style = 'blue'
format = '[$symbol($version )]($style)'

[zig]
style = 'yellow'
format = '[$symbol($version )]($style)'

[os.symbols]
AlmaLinux = " "
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = "󰌽 "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
RedHatEnterprise = " "
Redhat = " "
Redox = "󰀘 "
RockyLinux = " "
SUSE = " "
Solus = "󰠳 "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
openSUSE = " "

[palettes.mocha]
base = "#1e1e2e"
blue = "#89b4fa"
crust = "#11111b"
flamingo = "#f2cdcd"
green = "#a6e3a1"
lavender = "#b4befe"
mantle = "#181825"
maroon = "#eba0ac"
mauve = "#cba6f7"
overlay0 = "#6c7086"
overlay1 = "#7f849c"
overlay2 = "#9399b2"
peach = "#fab387"
pink = "#f5c2e7"
red = "#f38ba8"
rosewater = "#f5e0dc"
sapphire = "#74c7ec"
sky = "#89dceb"
subtext0 = "#a6adc8"
subtext1 = "#bac2de"
surface0 = "#313244"
surface1 = "#45475a"
surface2 = "#585b70"
teal = "#94e2d5"
text = "#cdd6f4"
yellow = "#f9e2af"
