-- Options are automatically loaded before lazy.nvim startup
-- Default options that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/options.lua
-- Add any additional options here
--
-- local g = vim.g
-- local o = vim.opt
--
-- -- LazyVim config choices
-- g.lazyvim_cmp = "blink"
-- g.lazyvim_picker = "snacks"
--
-- -- Root dir detection (expanded patterns)
-- g.root_spec = {
--   "lsp",
--   { ".git", "lua", ".obsidian", "package.json", "Makefile", "go.mod", "cargo.toml", "pyproject.toml", "src" },
--   "cwd",
-- }
--
-- -- Minimal UI
-- o.cmdheight = 0
-- o.showcmd = false
-- o.showtabline = 0
--
-- -- Spelling (English only)
-- o.spell = true
-- o.spelllang = { "en" }
--
-- -- Better indentation on wrap
-- o.breakindent = true
--
-- -- Font (for GUI Neovim like Neovide)
-- g.gui_font_default_size = 10
-- g.gui_font_size = g.gui_font_default_size
-- g.gui_font_face = "FantasqueSansM Nerd Font"
--
-- -- WSL clipboard fix
-- if os.getenv("WSL_DISTRO_NAME") ~= nil then
--   o.clipboard = "unnamedplus"
-- end
--
-- -- Windows shell fixes
-- if vim.fn.has("win32") == 1 or vim.fn.has("win64") == 1 then
--   o.shell = "cmd.exe"
--   o.shellcmdflag = "/s /c"
--   o.shellxquote = '"'
--   o.shellquote = ""
--   o.shellpipe = ">%s 2>&1"
--   o.shellredir = ">%s 2>&1"
--   if os.getenv("TERM") then
--     o.termguicolors = true
--   end
-- end
